--------------------------------------------------------
--  DDL for Table MT_ITEM_OE_BOM_LIST
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_ITEM_OE_BOM_LIST" 
   (	"OE_CODE" VARCHAR2(20 BYTE), 
	"ITEM_ID" VARCHAR2(20 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APEX_1845682454237562" ;
