--------------------------------------------------------
--  DDL for Table ATL_MASTER_ERROR_DETAILS
--------------------------------------------------------

  CREATE TABLE "ATOM"."ATL_MASTER_ERROR_DETAILS" 
   (	"ERROR_SEQ_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PACKAGE_NAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"PROC_FUNC_NAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"MASTER_ENTITY_NAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"LINE_NO" NUMBER DEFAULT NULL, 
	"SQL_ERROR_CODE" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"SQL_ERROR_MESSAGE" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"ATTRIBUTE1" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"ATTRIBUTE2" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"ATTRIBUTE3" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"ATTRIBUTE4" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"ATTRIBUTE5" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"CREATED_BY" VARCHAR2(100 BYTE) DEFAULT '-1', 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE) DEFAULT '-1', 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"LAST_UPDATE_LOGIN" VARCHAR2(100 BYTE) DEFAULT '-1'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
