--------------------------------------------------------
--  DDL for Table CLS_FILE_DATA
--------------------------------------------------------

  CREATE TABLE "ATOM"."CLS_FILE_DATA" 
   (	"ID" NUMBER, 
	"FLOW_ID" NUMBER, 
	"NAME" VARCHAR2(400 BYTE), 
	"PATHID" NUMBER, 
	"FILENAME" VARCHAR2(400 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"MIME_TYPE" VARCHAR2(255 BYTE), 
	"DOC_SIZE" NUMBER, 
	"DAD_CHARSET" VARCHAR2(128 BYTE), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED_ON" DATE, 
	"DELETED_AS_OF" DATE, 
	"LAST_UPDATED" DATE, 
	"CONTENT_TYPE" VARCHAR2(128 BYTE), 
	"BLOB_CONTENT" BLOB, 
	"LANGUAGE" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"SECURITY_GROUP_ID" NUMBER, 
	"FILE_TYPE" VARCHAR2(255 BYTE), 
	"FILE_CHARSET" VARCHAR2(128 BYTE), 
	"SESSION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" 
 LOB ("BLOB_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "APEX_1845682454237562" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
