--------------------------------------------------------
--  DDL for Table CT_COUNTRY
--------------------------------------------------------

  CREATE TABLE "ATOM"."CT_COUNTRY" 
   (	"COUNTRY_CODE" VARCHAR2(20 BYTE), 
	"COUNTRY_NAME" VARCHAR2(50 BYTE), 
	"IS_EXPORT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
