--------------------------------------------------------
--  DDL for Table CT_OTM_FREIGHT_BASIS
--------------------------------------------------------

  CREATE TABLE "ATOM"."CT_OTM_FREIGHT_BASIS" 
   (	"BASIS" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"IN_PAAS" VARCHAR2(20 BYTE), 
	"IN_OTM" VARCHAR2(20 BYTE), 
	"OTM_BASIS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
