--------------------------------------------------------
--  DDL for Table CT_RATE_TYPE_LOOKUP
--------------------------------------------------------

  CREATE TABLE "ATOM"."CT_RATE_TYPE_LOOKUP" 
   (	"RATE_TYPE" VARCHAR2(100 BYTE), 
	"DETENTION_CODE" VARCHAR2(100 BYTE), 
	"PENALTY_CODE" VARCHAR2(100 BYTE), 
	"LOADING" VARCHAR2(1 BYTE), 
	"UNLOADING" VARCHAR2(1 BYTE), 
	"OTHERS1" VARCHAR2(1 BYTE), 
	"OTHERS2" VARCHAR2(1 BYTE), 
	"OTHERS3" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
