--------------------------------------------------------
--  DDL for Table CT_UOM_MAP
--------------------------------------------------------

  CREATE TABLE "ATOM"."CT_UOM_MAP" 
   (	"TYPE" VARCHAR2(20 BYTE), 
	"FROM_UOM_CODE" VARCHAR2(5 BYTE), 
	"TO_UOM_CODE" VARCHAR2(5 BYTE), 
	"CONVERSION_FACTOR" NUMBER, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
