--------------------------------------------------------
--  DDL for Table DEL_INV_HEADER
--------------------------------------------------------

  CREATE TABLE "ATOM"."DEL_INV_HEADER" 
   (	"LOADSLIP_ID" VARCHAR2(50 BYTE), 
	"SHIPMENT_ID" VARCHAR2(50 BYTE), 
	"INVOICE_NUMBER" VARCHAR2(100 BYTE), 
	"DELIVERY_NUMBER" VARCHAR2(100 BYTE), 
	"SO_STO_NUM" VARCHAR2(100 BYTE), 
	"INVOICE_DATE" DATE, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" VARCHAR2(20 BYTE), 
	"LR_NUMBER" VARCHAR2(100 BYTE), 
	"TRUCK_NUMBER" VARCHAR2(100 BYTE), 
	"SOURCE_LOC" VARCHAR2(20 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"LR_DATE" DATE, 
	"CONTAINER_NUM" VARCHAR2(11 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"POL" VARCHAR2(100 BYTE), 
	"POD" VARCHAR2(100 BYTE), 
	"INCOTERM" VARCHAR2(10 BYTE), 
	"INCOTERM_LOC" VARCHAR2(50 BYTE), 
	"BILL_TO" VARCHAR2(30 BYTE), 
	"BILL_TO_NAME" VARCHAR2(200 BYTE), 
	"SHIP_TO" VARCHAR2(30 BYTE), 
	"SHIP_TO_NAME" VARCHAR2(200 BYTE), 
	"DEST_LOC_COUNTRY" VARCHAR2(3 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"SAP_INV_VALUE" NUMBER, 
	"E_WAY_BILL_NO" VARCHAR2(200 BYTE), 
	"E_WAY_BILL_DATE" DATE, 
	"TOTAL_WEIGHT" NUMBER, 
	"TOTAL_WEIGHT_UOM" VARCHAR2(5 BYTE), 
	"CUSTOM_INV_NUMBER" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."DEL_INV_HEADER"."STATUS" IS 'OPEN, CLOSED';
   COMMENT ON COLUMN "ATOM"."DEL_INV_HEADER"."TYPE" IS 'FGS_EXP, FGS_JIT';
