--------------------------------------------------------
--  DDL for Table DISPATCH_PLAN
--------------------------------------------------------

  CREATE TABLE "ATOM"."DISPATCH_PLAN" 
   (	"ID" NUMBER, 
	"DISPATCH_PLAN_ID" NUMBER(*,0), 
	"LINE_NUM" NUMBER, 
	"DISPATCH_DATE" DATE, 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"SOURCE_LOC" VARCHAR2(20 BYTE), 
	"ITEM_ID" VARCHAR2(20 BYTE), 
	"ITEM_DESCRIPTION" VARCHAR2(200 BYTE), 
	"ITEM_CATEGORY" VARCHAR2(20 BYTE), 
	"TTE" NUMBER, 
	"BATCH_CODE" VARCHAR2(10 BYTE), 
	"QUANTITY" NUMBER, 
	"PRIORITY" NUMBER, 
	"MARKET_SEGMENT" VARCHAR2(10 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"APP_STATUS" VARCHAR2(50 BYTE), 
	"APPROVED_QTY" NUMBER, 
	"DELETED_QTY" NUMBER, 
	"AVAIL_QTY" NUMBER, 
	"RESERVED_QTY" NUMBER, 
	"DISPATCHED_QTY" NUMBER, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"DEST_DESCRIPTION" VARCHAR2(200 BYTE), 
	"COMMENTS" VARCHAR2(200 BYTE), 
	"UNAPP_QTY" NUMBER DEFAULT 0, 
	"TOT_AVAIL_QTY" NUMBER DEFAULT 0, 
	"UNAPP_DEL_QTY" NUMBER DEFAULT 0, 
	"LOADED_QTY" NUMBER DEFAULT 0, 
	"WEIGHT" NUMBER, 
	"WEIGHT_UOM" VARCHAR2(5 BYTE) DEFAULT 'KG', 
	"VOLUME" NUMBER, 
	"VOLUME_UOM" VARCHAR2(5 BYTE) DEFAULT 'CUMTR'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
