--------------------------------------------------------
--  DDL for Table DISPATCH_PLAN_BOM
--------------------------------------------------------

  CREATE TABLE "ATOM"."DISPATCH_PLAN_BOM" 
   (	"DISPATCH_PLAN_ID" NUMBER, 
	"LINE_NUM" NUMBER, 
	"ITEM_ID" VARCHAR2(20 BYTE), 
	"TUBE_CODE" VARCHAR2(20 BYTE), 
	"TUBE_DESC" VARCHAR2(200 BYTE), 
	"TUBE_COMP_QTY" NUMBER, 
	"FLAP_CODE" VARCHAR2(20 BYTE), 
	"FLAP_DESC" VARCHAR2(200 BYTE), 
	"FLAP_COMP_QTY" NUMBER, 
	"VALVE_CODE" VARCHAR2(20 BYTE), 
	"VALVE_DESC" VARCHAR2(200 BYTE), 
	"VALVE_COMP_QTY" NUMBER, 
	"WEIGHT" NUMBER, 
	"WEIGHT_UOM" VARCHAR2(5 BYTE), 
	"VOLUME" NUMBER, 
	"VOLUME_UOM" VARCHAR2(5 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
