--------------------------------------------------------
--  DDL for Table DISPATCH_PLAN_SUMMARY
--------------------------------------------------------

  CREATE TABLE "ATOM"."DISPATCH_PLAN_SUMMARY" 
   (	"SOURCE_LOC" VARCHAR2(20 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"DISPATCH_DAE" DATE, 
	"TOTAL_PLAN_TTE" NUMBER, 
	"TOTAL_DISP_TTE" NUMBER, 
	"TOTAL_BALANCE_TTE" NUMBER, 
	"TOTAL_DISPATCH_PCT" NUMBER, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."DISPATCH_PLAN_SUMMARY"."TOTAL_PLAN_TTE" IS 'Sum of all (QUANTITY.TTE) for the given dispatch date + Source + Destination location';
   COMMENT ON COLUMN "ATOM"."DISPATCH_PLAN_SUMMARY"."TOTAL_DISP_TTE" IS 'Sum of all (DISPATCHED_QTY.TTE) for the given dispatch date + Source + Destination location';
   COMMENT ON COLUMN "ATOM"."DISPATCH_PLAN_SUMMARY"."TOTAL_BALANCE_TTE" IS 'TOTAL_PLAN_TTE – TOTAL_DISP_TTE';
   COMMENT ON COLUMN "ATOM"."DISPATCH_PLAN_SUMMARY"."TOTAL_DISPATCH_PCT" IS '(TOTAL_DISP_TTE / TOTAL_PLAN_TTE) * 100';
