--------------------------------------------------------
--  DDL for Table FREIGHT_TEMP
--------------------------------------------------------

  CREATE TABLE "ATOM"."FREIGHT_TEMP" 
   (	"ID" NUMBER, 
	"TRANSPORTER_SAP_CODE" VARCHAR2(20 BYTE), 
	"SERVPROV" VARCHAR2(30 BYTE), 
	"SOURCE_LOC" VARCHAR2(20 BYTE), 
	"SOURCE_DESC" VARCHAR2(200 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"DEST_DESC" VARCHAR2(200 BYTE), 
	"LANE_CODE" VARCHAR2(50 BYTE), 
	"TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"CONDITION1" VARCHAR2(200 BYTE), 
	"CONDITION2" VARCHAR2(800 BYTE), 
	"EFFECTIVE_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"TT_DAYS" NUMBER, 
	"BASE_FREIGHT" NUMBER, 
	"BASE_FREIGHT_UOM" VARCHAR2(5 BYTE), 
	"BASIS" VARCHAR2(20 BYTE), 
	"MIN_VALUE" NUMBER, 
	"MIN_VALUE_UOM" VARCHAR2(5 BYTE), 
	"TRANSPORT_MODE" VARCHAR2(50 BYTE), 
	"APPROVAL1_USER" VARCHAR2(20 BYTE), 
	"APPROVAL1_DATE" DATE, 
	"APPROVAL2_USER" VARCHAR2(20 BYTE), 
	"APPROVAL2_DATE" DATE, 
	"STATUS" VARCHAR2(10 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(2400 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"RATE_TYPE" VARCHAR2(20 BYTE), 
	"LOADING" NUMBER, 
	"UNLOADING" NUMBER, 
	"OTHERS1" NUMBER, 
	"OTHERS1_CODE" VARCHAR2(100 BYTE), 
	"OTHERS2" NUMBER, 
	"OTHERS2_CODE" VARCHAR2(100 BYTE), 
	"OTHERS3" NUMBER, 
	"OTHERS3_CODE" VARCHAR2(100 BYTE), 
	"DISTANCE" NUMBER, 
	"TOTAL_EXPENSE" NUMBER, 
	"PAYABLE_TRANSPORTER" NUMBER, 
	"SOURCE_TYPE" VARCHAR2(20 BYTE), 
	"REMARKS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
