--------------------------------------------------------
--  DDL for Table FREIGHT
--------------------------------------------------------

  CREATE TABLE "ATOM"."FREIGHT" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10372 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TRANSPORTER_SAP_CODE" VARCHAR2(20 BYTE), 
	"SERVPROV" VARCHAR2(30 BYTE), 
	"SOURCE_LOC" VARCHAR2(20 BYTE), 
	"SOURCE_DESC" VARCHAR2(200 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"DEST_DESC" VARCHAR2(200 BYTE), 
	"LANE_CODE" VARCHAR2(50 BYTE), 
	"TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"CONDITION1" VARCHAR2(200 BYTE), 
	"CONDITION2" VARCHAR2(800 BYTE), 
	"EFFECTIVE_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"TT_DAYS" NUMBER, 
	"BASE_FREIGHT" NUMBER, 
	"BASE_FREIGHT_UOM" VARCHAR2(5 BYTE), 
	"BASIS" VARCHAR2(20 BYTE), 
	"MIN_VALUE" NUMBER, 
	"MIN_VALUE_UOM" VARCHAR2(5 BYTE), 
	"APPROVAL1_USER" VARCHAR2(20 BYTE), 
	"APPROVAL1_DATE" DATE, 
	"APPROVAL2_USER" VARCHAR2(20 BYTE), 
	"APPROVAL2_DATE" DATE, 
	"STATUS" VARCHAR2(20 BYTE), 
	"TRANSPORT_MODE" VARCHAR2(20 BYTE), 
	"PREVIOUS_RATE" NUMBER, 
	"DIFF" VARCHAR2(10 BYTE), 
	"PERCENTILE" VARCHAR2(10 BYTE), 
	"RATE_RECORD_ID" VARCHAR2(1000 BYTE), 
	"OTM_REF_TRANS_NO" VARCHAR2(100 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"RATE_TYPE" VARCHAR2(20 BYTE), 
	"LOADING" NUMBER, 
	"UNLOADING" NUMBER, 
	"OTHERS1" NUMBER, 
	"OTHERS1_CODE" VARCHAR2(100 BYTE), 
	"OTHERS2" NUMBER, 
	"OTHERS2_CODE" VARCHAR2(100 BYTE), 
	"OTHERS3" NUMBER, 
	"OTHERS3_CODE" VARCHAR2(100 BYTE), 
	"DISTANCE" NUMBER, 
	"TOTAL_EXPENSE" NUMBER, 
	"PAYABLE_TRANSPORTER" NUMBER, 
	"SOURCE_TYPE" VARCHAR2(20 BYTE), 
	"OTM_RR_ID" VARCHAR2(400 BYTE), 
	"REMARKS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."FREIGHT"."CONDITION1" IS 'Used for recording truck variant 1, in case of dedicated trucks, the truck number dedicated for the movement will be recorded from TRUCK_REPORTING table and copied on to the Shipment in OPS if present in the FREIGHT_LANE_DEDICATED_TRUCK table';
   COMMENT ON COLUMN "ATOM"."FREIGHT"."TT_DAYS" IS 'Transit time';
   COMMENT ON COLUMN "ATOM"."FREIGHT"."BASIS" IS 'Basis for calculation e.g. PER_TRUCK, PER_KM, PER_TYRE etc.';
   COMMENT ON COLUMN "ATOM"."FREIGHT"."STATUS" IS 'Status of the rate, CREATED, APPROVED1, APPROVED2';
