--------------------------------------------------------
--  DDL for Table GRN_HEADER
--------------------------------------------------------

  CREATE TABLE "ATOM"."GRN_HEADER" 
   (	"LOADSLIP_ID" VARCHAR2(50 BYTE), 
	"SHIPMENT_ID" VARCHAR2(50 BYTE), 
	"GRN_TYPE" VARCHAR2(10 BYTE), 
	"STO_PO_NUM" VARCHAR2(100 BYTE), 
	"DELIVERY_NUM" VARCHAR2(100 BYTE), 
	"LR_NUMBER" VARCHAR2(50 BYTE), 
	"TRUCK_REG_NUMBER" VARCHAR2(50 BYTE), 
	"VENDOR_NUMBER" VARCHAR2(100 BYTE), 
	"SOURCE_LOC" VARCHAR2(20 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"GRN_NUMBER" VARCHAR2(100 BYTE), 
	"GRN_DATE" DATE, 
	"REPORTING_DATE" DATE, 
	"UNLOADING_DATE" DATE, 
	"REMARKS" VARCHAR2(400 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
