--------------------------------------------------------
--  DDL for Table INDENT_SUMMARY
--------------------------------------------------------

  CREATE TABLE "ATOM"."INDENT_SUMMARY" 
   (	"ID" NUMBER, 
	"INDENT_ID" VARCHAR2(100 BYTE), 
	"DISPATCH_DATE" DATE, 
	"SOURCE_LOC" VARCHAR2(20 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"LOAD_FACTOR" NUMBER, 
	"SERVPROV" VARCHAR2(20 BYTE), 
	"ITEM_CATEGORY" VARCHAR2(20 BYTE), 
	"TTE_CAPACITY" NUMBER, 
	"INDENTED" NUMBER, 
	"CANCELLED" NUMBER, 
	"NET_REQUESTED" NUMBER, 
	"TRANS_CONFIRMED" NUMBER, 
	"TRANS_DECLINED" NUMBER, 
	"TRANS_ASSIGNED" NUMBER, 
	"REPORTED" NUMBER, 
	"REJECTED" NUMBER, 
	"NET_PLACED" NUMBER, 
	"NET_BALANCE" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"INDENT_COMMENTS" VARCHAR2(200 BYTE), 
	"INDENT_AGING" NUMBER, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"DEST_DESC" VARCHAR2(200 BYTE), 
	"FRT_AVAIL_FLAG" VARCHAR2(1 BYTE), 
	"DEST_COUNTRY" VARCHAR2(5 BYTE), 
	"POD" VARCHAR2(20 BYTE), 
	"DEST_DESCRIPTION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."INDENT_SUMMARY"."FRT_AVAIL_FLAG" IS 'Y or N';
