--------------------------------------------------------
--  DDL for Table INTEGRATION_ERRORS
--------------------------------------------------------

  CREATE TABLE "ATOM"."INTEGRATION_ERRORS" 
   (	"ERROR_REC_ID" NUMBER, 
	"API_NAME" VARCHAR2(200 BYTE), 
	"ERROR_DESC" VARCHAR2(4000 BYTE), 
	"ERROR_CODE" NUMBER, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
