--------------------------------------------------------
--  DDL for Table LOADSLIP
--------------------------------------------------------

  CREATE TABLE "ATOM"."LOADSLIP" 
   (	"LOADSLIP_ID" VARCHAR2(100 BYTE), 
	"LOADSLIP_NAME" VARCHAR2(100 BYTE), 
	"LOADSLIP_TYPE" VARCHAR2(20 BYTE), 
	"SHIPMENT_ID" VARCHAR2(100 BYTE), 
	"SOURCE_LOC" VARCHAR2(20 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"SHIP_TO" VARCHAR2(20 BYTE), 
	"LR_NUM" VARCHAR2(400 BYTE), 
	"LR_DATE" DATE, 
	"BAY" VARCHAR2(20 BYTE), 
	"STO_SO_NUM" VARCHAR2(400 BYTE), 
	"PO_NUM" VARCHAR2(100 BYTE), 
	"DELIVERY" VARCHAR2(400 BYTE), 
	"SAP_INVOICE" VARCHAR2(400 BYTE), 
	"SAP_INVOICE_DATE" DATE, 
	"GRN" VARCHAR2(400 BYTE), 
	"GRN_DATE" DATE, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"QTY" NUMBER, 
	"TTE_QTY" NUMBER, 
	"WEIGHT" NUMBER, 
	"WEIGHT_UOM" VARCHAR2(5 BYTE), 
	"VOLUME" NUMBER, 
	"VOLUME_UOM" VARCHAR2(5 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"LOAD_SEQ" NUMBER, 
	"DROP_SEQ" NUMBER, 
	"ARRIVED_DATE" DATE, 
	"LSPRINT_DATE" DATE, 
	"LS_DATE" DATE, 
	"LE_DATE" DATE, 
	"CONFIRM_DATE" DATE, 
	"RELEASE_DATE" DATE, 
	"US_DATE" DATE, 
	"UE_DATE" DATE, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"TOT_TYRES" NUMBER, 
	"TOT_TUBES" NUMBER, 
	"TOT_FLAPS" NUMBER, 
	"TOT_VALVE" NUMBER, 
	"TTE_UTIL" NUMBER, 
	"ITEM_CATEGORY" VARCHAR2(20 BYTE), 
	"WEIGHT_UTIL" NUMBER, 
	"VOLUME_UTIL" NUMBER, 
	"SEND_FOR_BARCODE_DATE" DATE, 
	"GRN_REMARK" VARCHAR2(200 BYTE), 
	"GRN_REPORTING_DATE" DATE, 
	"GRN_UNLOADING_DATE" DATE, 
	"INT_STATUS" VARCHAR2(10 BYTE), 
	"INT_MESSAGE" VARCHAR2(4000 BYTE), 
	"TOT_PCTR" NUMBER DEFAULT 0, 
	"TOT_QTY" NUMBER DEFAULT 0, 
	"COMMENTS" VARCHAR2(200 BYTE), 
	"SHORT_QTY" NUMBER, 
	"DIT_QTY" NUMBER, 
	"SAP_INV_VALUE" NUMBER, 
	"SAP_INV_WEIGHT" NUMBER, 
	"E_WAY_BILL_NO" VARCHAR2(200 BYTE), 
	"MKT_SEG" VARCHAR2(20 BYTE), 
	"OTHER" NUMBER DEFAULT 0, 
	"E_WAY_BILL_DATE" DATE, 
	"CUSTOM_INV_NUMBER" VARCHAR2(2000 BYTE), 
	"USAGE_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."LOADSLIP"."TTE_QTY" IS 'Sum of (QTY x TTE)';
   COMMENT ON COLUMN "ATOM"."LOADSLIP"."TTE_UTIL" IS 'TTE utilization';
   COMMENT ON COLUMN "ATOM"."LOADSLIP"."SEND_FOR_BARCODE_DATE" IS 'sent for Barcode scannin';
