--------------------------------------------------------
--  DDL for Table LOADSLIP_DETAIL
--------------------------------------------------------

  CREATE TABLE "ATOM"."LOADSLIP_DETAIL" 
   (	"LOADSLIP_ID" VARCHAR2(50 BYTE), 
	"LINE_NO" NUMBER, 
	"ITEM_ID" VARCHAR2(50 BYTE), 
	"ITEM_DESCRIPTION" VARCHAR2(200 BYTE), 
	"BATCH_CODE" VARCHAR2(20 BYTE), 
	"LOAD_QTY" NUMBER, 
	"GROSS_WT" NUMBER, 
	"GROSS_WT_UOM" VARCHAR2(5 BYTE), 
	"GROSS_VOL" NUMBER, 
	"GROSS_VOL_UOM" VARCHAR2(5 BYTE), 
	"TTE" NUMBER, 
	"SCANNABLE" VARCHAR2(1 BYTE), 
	"SCANNED_QTY" NUMBER, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"INVOICE_NUMBER" VARCHAR2(20 BYTE), 
	"IS_SPLIT" VARCHAR2(1 BYTE), 
	"IS_LOADED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ITEM_CATEGORY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."LOADSLIP_DETAIL"."INVOICE_NUMBER" IS 'For Export and JIT';
   COMMENT ON COLUMN "ATOM"."LOADSLIP_DETAIL"."IS_SPLIT" IS 'To understand Item is splitted or not';
