--------------------------------------------------------
--  DDL for Table LOADSLIP_INV_HEADER
--------------------------------------------------------

  CREATE TABLE "ATOM"."LOADSLIP_INV_HEADER" 
   (	"LOADSLIP_ID" VARCHAR2(50 BYTE), 
	"SHIPMENT_ID" VARCHAR2(50 BYTE), 
	"INVOICE_NUMBER" VARCHAR2(100 BYTE), 
	"DELIVERY_NUMBER" VARCHAR2(100 BYTE), 
	"SO_STO_NUM" VARCHAR2(100 BYTE), 
	"INVOICE_DATE" DATE, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" VARCHAR2(20 BYTE), 
	"LR_NUMBER" VARCHAR2(100 BYTE), 
	"TRUCK_NUMBER" VARCHAR2(100 BYTE), 
	"SOURCE_LOC" VARCHAR2(20 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"LR_DATE" DATE, 
	"SAP_INV_VALUE" NUMBER, 
	"E_WAY_BILL_NO" VARCHAR2(200 BYTE), 
	"E_WAY_BILL_DATE" DATE, 
	"TOTAL_WEIGHT" NUMBER, 
	"TOTAL_WEIGHT_UOM" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
