--------------------------------------------------------
--  DDL for Table LOADSLIP_DETAIL_BOM
--------------------------------------------------------

  CREATE TABLE "ATOM"."LOADSLIP_DETAIL_BOM" 
   (	"LOADSLIP_ID" VARCHAR2(50 BYTE), 
	"ITEM_ID" VARCHAR2(20 BYTE), 
	"TUBE_SKU" VARCHAR2(20 BYTE), 
	"FLAP_SKU" VARCHAR2(20 BYTE), 
	"VALVE_SKU" VARCHAR2(20 BYTE), 
	"TUBE_BATCH" VARCHAR2(20 BYTE), 
	"FLAP_BATCH" VARCHAR2(20 BYTE), 
	"VALVE_BATCH" VARCHAR2(20 BYTE), 
	"TUBE_QTY" NUMBER, 
	"FLAP_QTY" NUMBER, 
	"VALVE_QTY" NUMBER, 
	"INSERT_USER" VARCHAR2(50 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"LINE_NO" NUMBER, 
	"TUBE_DESC" VARCHAR2(200 BYTE), 
	"FLAP_DEC" VARCHAR2(200 BYTE), 
	"VALVE_DESC" VARCHAR2(200 BYTE), 
	"PCTR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
