--------------------------------------------------------
--  DDL for Table LOCATION_SCAN
--------------------------------------------------------

  CREATE TABLE "ATOM"."LOCATION_SCAN" 
   (	"LOCATION_ID" VARCHAR2(20 BYTE), 
	"SCANNABLE" VARCHAR2(1 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"ITEM_CATEGORY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."LOCATION_SCAN"."ITEM_CATEGORY" IS 'Material Group like PCR , TBB etc';
