--------------------------------------------------------
--  DDL for Table MT_CONTACT
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_CONTACT" 
   (	"CONTACT_ID" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"MOBILE" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"LOCATION_ID" VARCHAR2(20 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
