--------------------------------------------------------
--  DDL for Table MT_DRIVER
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_DRIVER" 
   (	"LICENCE_NUMBER" VARCHAR2(50 BYTE), 
	"DRIVER_NAME" VARCHAR2(50 BYTE), 
	"MOBILE_NUMBER" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."MT_DRIVER"."STATUS" IS 'Check if driver is blacklisted for Apollo.';
