--------------------------------------------------------
--  DDL for Table MT_EXT_WAREHOUSE
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_EXT_WAREHOUSE" 
   (	"LOCATION_ID" VARCHAR2(50 BYTE), 
	"LOCATION_DESC" VARCHAR2(200 BYTE), 
	"LOCATION_TYPE" VARCHAR2(20 BYTE), 
	"LOCATION_ADDRESS" VARCHAR2(400 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"POSTAL_CODE" VARCHAR2(20 BYTE), 
	"COUNTRY" VARCHAR2(3 BYTE), 
	"IS_ACTIVE" VARCHAR2(1 BYTE), 
	"LAT" NUMBER(11,8), 
	"LON" NUMBER(11,8), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"STATE_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
