--------------------------------------------------------
--  DDL for Table MT_ELR
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_ELR" 
   (	"LOCATION_ID" VARCHAR2(20 BYTE), 
	"SERVPROV" VARCHAR2(20 BYTE), 
	"ELR_FLAG" VARCHAR2(1 BYTE), 
	"INSERT_USER" VARCHAR2(50 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(50 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
