--------------------------------------------------------
--  DDL for Table MT_ITEM_PLANT_WEIGHT
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_ITEM_PLANT_WEIGHT" 
   (	"PLANT_CODE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_DATE" DATE, 
	"ITEM_ID" VARCHAR2(20 BYTE), 
	"WEIGHT" NUMBER, 
	"WEIGHT_UOM" VARCHAR2(5 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
