--------------------------------------------------------
--  DDL for Table MT_ITEM
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_ITEM" 
   (	"ITEM_ID" VARCHAR2(20 BYTE), 
	"ITEM_CLASSIFICATION" VARCHAR2(20 BYTE), 
	"ITEM_DESCRIPTION" VARCHAR2(200 BYTE), 
	"ITEM_TYPE" VARCHAR2(10 BYTE), 
	"ITEM_GROUP" VARCHAR2(20 BYTE), 
	"TTE" NUMBER(*,2), 
	"LOAD_FACTOR" NUMBER, 
	"GROSS_WT" NUMBER, 
	"GROSS_WT_UOM" VARCHAR2(5 BYTE), 
	"NET_WT" NUMBER, 
	"NET_WT_UOM" VARCHAR2(5 BYTE), 
	"VOLUME" NUMBER, 
	"VOL_UOM" VARCHAR2(5 BYTE), 
	"LENGTH" NUMBER, 
	"LEN_UOM" VARCHAR2(5 BYTE), 
	"WIDTH" NUMBER, 
	"WD_UOM" VARCHAR2(5 BYTE), 
	"HEIGHT" NUMBER, 
	"HT_UOM" VARCHAR2(5 BYTE), 
	"DIAMETER" NUMBER, 
	"DM_UOM" VARCHAR2(5 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"ITEM_CATEGORY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."MT_ITEM"."ITEM_CLASSIFICATION" IS 'Material Category (Tyre / Tube / Flap / Valve) identification from SAP';
   COMMENT ON COLUMN "ATOM"."MT_ITEM"."ITEM_TYPE" IS 'Material Type (FGS / RMS / EMS / ENG / SFG)';
   COMMENT ON COLUMN "ATOM"."MT_ITEM"."ITEM_GROUP" IS 'Material Group (R01, R02 TO R17 for RMS. 
R5, R1, R2, R6, R7, RZ to be filtered from SAP before interfacing. 
2WHBT, TRKBT, TRKRT)';
   COMMENT ON COLUMN "ATOM"."MT_ITEM"."ITEM_CATEGORY" IS 'This will be a roll up category maintained by SCM team';
