--------------------------------------------------------
--  DDL for Table MT_INCOTERMS
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_INCOTERMS" 
   (	"INCOTERM_CODE" VARCHAR2(3 BYTE), 
	"INCOTERM_DESC" VARCHAR2(20 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APEX_1845682454237562" ;
