--------------------------------------------------------
--  DDL for Table MT_LANE
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_LANE" 
   (	"LANE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"SOURCE_LOCATION_ID" VARCHAR2(50 BYTE), 
	"DEST_LOCATION_ID" VARCHAR2(50 BYTE), 
	"DISTANCE" NUMBER, 
	"UOM" VARCHAR2(50 BYTE), 
	"INSERT_USER" VARCHAR2(50 BYTE), 
	"UPDATE_USER" VARCHAR2(50 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APEX_1845682454237562" ;
