--------------------------------------------------------
--  DDL for Table MT_LOCATION
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_LOCATION" 
   (	"LOCATION_ID" VARCHAR2(50 BYTE), 
	"LOCATION_DESC" VARCHAR2(200 BYTE), 
	"LOCATION_TYPE" VARCHAR2(20 BYTE), 
	"LOCATION_ADDRESS" VARCHAR2(400 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"STATE_CODE" NUMBER, 
	"POSTAL_CODE" VARCHAR2(20 BYTE), 
	"COUNTRY" VARCHAR2(3 BYTE), 
	"IS_ACTIVE" VARCHAR2(1 BYTE), 
	"LAT" NUMBER(11,8), 
	"LON" NUMBER(11,8), 
	"GST_NO" VARCHAR2(100 BYTE), 
	"GST_STATE" VARCHAR2(10 BYTE), 
	"PAN_NO" VARCHAR2(20 BYTE), 
	"FT_ACCESS_KEY" VARCHAR2(2000 BYTE), 
	"LOCATION_CLASS" VARCHAR2(20 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"LINKED_PLANT" VARCHAR2(50 BYTE), 
	"EMAIL_ID" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."MT_LOCATION"."LOCATION_TYPE" IS 'IT IS USED TO CPATURE WHETHER LOCATION IS PLANT,OE,RDC,ABU';
   COMMENT ON COLUMN "ATOM"."MT_LOCATION"."LAT" IS 'LATTITUDE';
   COMMENT ON COLUMN "ATOM"."MT_LOCATION"."LON" IS 'LONGITUDE';
   COMMENT ON COLUMN "ATOM"."MT_LOCATION"."LOCATION_CLASS" IS 'EXTERNAL/EXPOR Warehouses';
