--------------------------------------------------------
--  DDL for Table MT_MATERIAL_GROUP
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_MATERIAL_GROUP" 
   (	"MATERIAL_GROUP_ID" VARCHAR2(20 BYTE), 
	"DESCRIPTION_1" VARCHAR2(200 BYTE), 
	"DESCRIPTION_2" VARCHAR2(200 BYTE), 
	"SCM_GROUP" VARCHAR2(20 BYTE), 
	"INSERT_USER" VARCHAR2(50 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(50 BYTE), 
	"UPDATE_DATE" DATE, 
	"MG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."MT_MATERIAL_GROUP"."SCM_GROUP" IS 'This will be updated by SCM team, manually';
