--------------------------------------------------------
--  DDL for Table MT_PLANT_BATCH
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_PLANT_BATCH" 
   (	"PLANT_ID" VARCHAR2(20 BYTE), 
	"BATCH_CODE" VARCHAR2(10 BYTE), 
	"ITEM_CLASSIFICATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
