--------------------------------------------------------
--  DDL for Table MT_SUPPLIER
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_SUPPLIER" 
   (	"SUPPLIER_ID" VARCHAR2(50 BYTE), 
	"SUPPLIER_NAME" VARCHAR2(200 BYTE), 
	"INDUSTRY_KEY" VARCHAR2(20 BYTE), 
	"SUPPLIER_ADDRESS" VARCHAR2(400 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"POSTAL_CODE" VARCHAR2(20 BYTE), 
	"COUNTRY" VARCHAR2(2 BYTE), 
	"LAT" NUMBER(11,8), 
	"LON" NUMBER(11,8), 
	"IS_ACTIVE" VARCHAR2(1 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"PUR_ORG" VARCHAR2(20 BYTE), 
	"STATE_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562"   NO INMEMORY ;

   COMMENT ON COLUMN "ATOM"."MT_SUPPLIER"."LAT" IS 'LATTITUDE';
   COMMENT ON COLUMN "ATOM"."MT_SUPPLIER"."LON" IS 'LONGITUDE';
