--------------------------------------------------------
--  DDL for Table MT_TRUCK_TYPE
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_TRUCK_TYPE" 
   (	"TRUCK_TYPE" VARCHAR2(50 BYTE), 
	"LOAD_FACTOR" NUMBER, 
	"TRUCK_DESC" VARCHAR2(50 BYTE), 
	"TTE_CAPACITY" NUMBER, 
	"GROSS_WT" NUMBER, 
	"GROSS_WT_UOM" VARCHAR2(5 BYTE), 
	"GROSS_VOL" NUMBER, 
	"GROSS_VOL_UOM" VARCHAR2(5 BYTE), 
	"VARIANT1" VARCHAR2(50 BYTE), 
	"VARIANT2" VARCHAR2(50 BYTE), 
	"TT_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 82 CACHE 10 NOORDER  CYCLE  NOKEEP  NOSCALE , 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
