--------------------------------------------------------
--  DDL for Table MT_TRUCK
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_TRUCK" 
   (	"TRUCK_NUMBER" VARCHAR2(20 BYTE), 
	"SERVPROV" VARCHAR2(20 BYTE), 
	"TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"TRUCK_BODY_TYPE" VARCHAR2(20 BYTE), 
	"VARIANT1" VARCHAR2(20 BYTE), 
	"VARIANT2" VARCHAR2(20 BYTE), 
	"GPS_ENABLED" VARCHAR2(1 BYTE), 
	"GPS_DEVICE_ID" VARCHAR2(200 BYTE), 
	"GPS_PROVIDER" VARCHAR2(100 BYTE), 
	"WIDTH" NUMBER, 
	"WIDTH_UOM" VARCHAR2(5 BYTE), 
	"HEIGHT" NUMBER, 
	"HEIGHT_UOM" VARCHAR2(5 BYTE), 
	"LENGTH" NUMBER, 
	"LENGTH_UOM" VARCHAR2(5 BYTE), 
	"TARE_WEIGHT" NUMBER, 
	"TARE_WEIGHT_UOM" VARCHAR2(5 BYTE), 
	"PASSING_WEIGHT" NUMBER, 
	"PASSING_WEIGHT_UOM" VARCHAR2(5 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'NORMAL', 
	"LAST_UPDATE_PLANTCODE" VARCHAR2(20 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"MAX_VOLUME" NUMBER, 
	"MAX_VOLUME_UOM" VARCHAR2(5 BYTE), 
	"TTE_CAPACITY" NUMBER, 
	"TT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."TRUCK_NUMBER" IS 'Truck registration number';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."SERVPROV" IS 'Transporter Name as defaulted by SCM';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."TRUCK_BODY_TYPE" IS 'Truck body type viz. Open, Closed etc.';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."GPS_ENABLED" IS 'Used to record if GPS is enabled or not';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."GPS_DEVICE_ID" IS 'Used to record the GPS device ID (not to be used now)';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."GPS_PROVIDER" IS 'Used to record the GPS service provider  Look up the MT_GPS_PROVIDER table';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."WIDTH" IS 'Width of truck (in meters) as updated by SCM team';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."HEIGHT" IS 'Height of truck (in meters) as updated by SCM team';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."LENGTH" IS 'Length of truck (in meters) as updated by SCM team';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."TARE_WEIGHT" IS 'Tare weight of truck (in KGS) as updated by SCM team';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."PASSING_WEIGHT" IS 'Passing weight of truck (in KGS) as updated by SCM team';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."STATUS" IS 'Status if the truck -> NORMAL or BLACKLISTED';
   COMMENT ON COLUMN "ATOM"."MT_TRUCK"."TTE_CAPACITY" IS 'Truck Load Factor';
