--------------------------------------------------------
--  DDL for Table MT_TRANSPORTER
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_TRANSPORTER" 
   (	"TRANSPORTER_ID" VARCHAR2(50 BYTE), 
	"TRANSPORTER_DESC" VARCHAR2(200 BYTE), 
	"SERVPROV" VARCHAR2(50 BYTE), 
	"TRANSPORTER_ADDRESS" VARCHAR2(400 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"STATE_CODE" VARCHAR2(10 BYTE), 
	"POSTAL_CODE" VARCHAR2(20 BYTE), 
	"COUNTRY" VARCHAR2(3 BYTE), 
	"IS_ACTIVE" VARCHAR2(1 BYTE), 
	"INDUSTRY_KEY" VARCHAR2(20 BYTE), 
	"GST_NO" VARCHAR2(100 BYTE), 
	"GST_STATE" VARCHAR2(20 BYTE), 
	"PAN_NO" VARCHAR2(20 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
