--------------------------------------------------------
--  DDL for Table MT_TRUCK_DEDICATED_AUDIT
--------------------------------------------------------

  CREATE TABLE "ATOM"."MT_TRUCK_DEDICATED_AUDIT" 
   (	"ID" NUMBER(*,0), 
	"SERPVORV" VARCHAR2(20 BYTE), 
	"SOURCE_LOC" VARCHAR2(20 BYTE), 
	"SOURCE_DESC" VARCHAR2(200 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"DEST_DESC" VARCHAR2(200 BYTE), 
	"TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"TRUCK_NUMBER" VARCHAR2(20 BYTE), 
	"EXPIRY_DATE" DATE, 
	"INSERT_DATE" DATE, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
