--------------------------------------------------------
--  DDL for Table ORDER_TYPE_LOOKUP
--------------------------------------------------------

  CREATE TABLE "ATOM"."ORDER_TYPE_LOOKUP" 
   (	"ORDER_TYPE" VARCHAR2(50 BYTE), 
	"MOVEMENT_TYPE" VARCHAR2(30 BYTE), 
	"MARKET_SEGMENT" VARCHAR2(20 BYTE), 
	"SAP_ORDER_TYPE" VARCHAR2(20 BYTE), 
	"SAP_DOC_TYPE" VARCHAR2(20 BYTE), 
	"INSERT_USER" VARCHAR2(50 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(50 BYTE), 
	"UPDATE_DATE" DATE, 
	"BOM_TYPE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
