--------------------------------------------------------
--  DDL for Table SHARED_TRUCK
--------------------------------------------------------

  CREATE TABLE "ATOM"."SHARED_TRUCK" 
   (	"SHIPMENT_ID" VARCHAR2(20 BYTE), 
	"PLANT_CODE" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."SHARED_TRUCK"."STATUS" IS 'OPEN,CLOSED';
