--------------------------------------------------------
--  DDL for Table SHIPMENT
--------------------------------------------------------

  CREATE TABLE "ATOM"."SHIPMENT" 
   (	"SHIPMENT_ID" VARCHAR2(50 BYTE), 
	"SHIPMENT_NAME" VARCHAR2(20 BYTE), 
	"SHIPMENT_TYPE" VARCHAR2(20 BYTE), 
	"SERVPROV" VARCHAR2(50 BYTE), 
	"TRANSPORTER_SAP_CODE" VARCHAR2(50 BYTE), 
	"TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"TRUCK_NUMBER" VARCHAR2(20 BYTE), 
	"ACTUAL_TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"VARIANT_1" VARCHAR2(20 BYTE), 
	"VARIANT_2" VARCHAR2(20 BYTE), 
	"INDENT_ID" VARCHAR2(100 BYTE), 
	"TRANSPORT_MODE" VARCHAR2(20 BYTE), 
	"DRIVER_LICENSE" VARCHAR2(50 BYTE), 
	"DRIVER_MOBILE" VARCHAR2(50 BYTE), 
	"DRIVER_NAME" VARCHAR2(100 BYTE), 
	"TRANSHIPMENT" VARCHAR2(1 BYTE), 
	"FREIGHT" NUMBER, 
	"FREIGHT_UOM" VARCHAR2(5 BYTE), 
	"STD_TT" NUMBER, 
	"SO_STO_NUM" VARCHAR2(100 BYTE), 
	"PO_NUM" VARCHAR2(100 BYTE), 
	"DELIVERY" VARCHAR2(100 BYTE), 
	"SAP_INVOICE" VARCHAR2(100 BYTE), 
	"SAP_INVOICE_DATE" DATE, 
	"GRN" VARCHAR2(100 BYTE), 
	"GRN_DATE" DATE, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"TOTAL_QTY" NUMBER, 
	"TOTAL_TTE" NUMBER, 
	"TOTAL_WEIGHT" NUMBER, 
	"TOTAL_WEIGHT_UOM" VARCHAR2(5 BYTE), 
	"TOTAL_VOLUME" NUMBER, 
	"TOTAL_VOLUME_UOM" VARCHAR2(5 BYTE), 
	"TTE_UTIL" NUMBER, 
	"WEIGHT_UTIL" NUMBER, 
	"VOLUME_UTIL" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"STOP_TYPE" VARCHAR2(10 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"FRT_AVAIL_FLAG" VARCHAR2(1 BYTE), 
	"CONTAINER_NUM" VARCHAR2(20 BYTE), 
	"GATEIN_DATE_CFS" DATE, 
	"GATEOUT_DATE_CFS" DATE, 
	"GATEIN_DATE_PORT" DATE, 
	"SHIPPED_ONBOARD_DATE" DATE, 
	"VESSEL_DEPART_POL_DATE" DATE, 
	"VESSEL_ARRIVE_POD_DATE" DATE, 
	"FT_TRIP_ID" VARCHAR2(200 BYTE), 
	"DEST_COUNTRY" VARCHAR2(5 BYTE), 
	"IS_SYNC_OTM" VARCHAR2(2 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."SHIPMENT"."STOP_TYPE" IS 'Stop type for the shipment viz. S (Single), MD (Multi-drop), MP (Multi-Pick), MPMD (multi-pick, multi-drop)';
   COMMENT ON COLUMN "ATOM"."SHIPMENT"."FRT_AVAIL_FLAG" IS 'Y or N';
