--------------------------------------------------------
--  DDL for Table SHIPMENT_STOP
--------------------------------------------------------

  CREATE TABLE "ATOM"."SHIPMENT_STOP" 
   (	"SHIPMENT_ID" VARCHAR2(20 BYTE), 
	"STOP_NUM" NUMBER, 
	"LOCATION_ID" VARCHAR2(20 BYTE), 
	"ACTIVITY" VARCHAR2(1 BYTE), 
	"LOADSLIP_ID" VARCHAR2(50 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"ACTUAL_ARRIVAL_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."SHIPMENT_STOP"."ACTIVITY" IS 'P or D';
