--------------------------------------------------------
--  DDL for Table SHIPMENT_EXPORT
--------------------------------------------------------

  CREATE TABLE "ATOM"."SHIPMENT_EXPORT" 
   (	"SHIPMENT_ID" VARCHAR2(200 BYTE), 
	"PI_NO" VARCHAR2(100 BYTE), 
	"CUSTOMER_NAME" VARCHAR2(100 BYTE), 
	"PRE_INV_NO" VARCHAR2(100 BYTE), 
	"INCO_TERM" VARCHAR2(10 BYTE), 
	"PAYMENT_TERMS" VARCHAR2(50 BYTE), 
	"POL" VARCHAR2(50 BYTE), 
	"POD" VARCHAR2(50 BYTE), 
	"COFD" VARCHAR2(50 BYTE), 
	"FORWARDER" VARCHAR2(50 BYTE), 
	"BILLING_PARTY" VARCHAR2(50 BYTE), 
	"SHIPPING_LINE" VARCHAR2(50 BYTE), 
	"CONTAINER_NUM" VARCHAR2(50 BYTE), 
	"CONT_PICK_DATE" DATE, 
	"STUFFING_DATE" DATE, 
	"BOOKING_NUM" VARCHAR2(50 BYTE), 
	"POST_INV_NO" VARCHAR2(50 BYTE), 
	"SAP_INVOICE" VARCHAR2(200 BYTE), 
	"INV_AMOUNT" VARCHAR2(50 BYTE), 
	"CHA" VARCHAR2(50 BYTE), 
	"PLANNED_VESSEL" VARCHAR2(50 BYTE), 
	"VESSEL_DEPART_POL_DATE" DATE, 
	"SHIPPING_BILL" VARCHAR2(50 BYTE), 
	"SHIPPING_BILL_DATE" DATE, 
	"GATEIN_DATE_CFS" DATE, 
	"CUSTOMS_EXAM_DATE" DATE, 
	"LEO_DATE" DATE, 
	"GATEOUT_DATE_CFS" DATE, 
	"GATEIN_DATE_PORT" DATE, 
	"ACTUAL_VESSEL" VARCHAR2(50 BYTE), 
	"SHIPPED_ONBOARD_DATE" DATE, 
	"ETA_POD" DATE, 
	"EXPORT_REMARKS" VARCHAR2(200 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"IS_SYNC_OTM" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"SOURCE_LOC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
