--------------------------------------------------------
--  DDL for Table TRUCK_REPORTING
--------------------------------------------------------

  CREATE TABLE "ATOM"."TRUCK_REPORTING" 
   (	"GATE_CONTROL_CODE" VARCHAR2(50 BYTE), 
	"INDENT_ID" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"TRANSPORTER_SAP_CODE" VARCHAR2(20 BYTE), 
	"CONTAINER_NUM" VARCHAR2(100 BYTE), 
	"CONTAINER_CODE" VARCHAR2(20 BYTE), 
	"TRUCK_NUMBER" VARCHAR2(20 BYTE), 
	"DRIVER_NAME" VARCHAR2(20 BYTE), 
	"DRIVER_MOBILE" VARCHAR2(20 BYTE), 
	"DRIVER_LICENSE" VARCHAR2(30 BYTE), 
	"SERVPROV" VARCHAR2(20 BYTE), 
	"TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"REPORTING_LOCATION" VARCHAR2(20 BYTE), 
	"SOURCE_LOC" VARCHAR2(20 BYTE), 
	"DEST_LOC" VARCHAR2(20 BYTE), 
	"REPORTING_DATE" DATE, 
	"GATEIN_DATE" DATE, 
	"GATEOUT_DATE" DATE, 
	"DEST_GEOFENCEIN_DATE" DATE, 
	"DEREPORTING_DATE" DATE, 
	"REP_GI_HRS" NUMBER, 
	"GI_GO_HRS" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"REJ_STATUS" VARCHAR2(20 BYTE), 
	"IN_WEIGHT" NUMBER, 
	"OUT_WEIGHT" NUMBER, 
	"NET_WEIGHT" NUMBER, 
	"BAY" VARCHAR2(20 BYTE), 
	"BAY_STATUS" VARCHAR2(20 BYTE), 
	"REJECTION_CODE" VARCHAR2(20 BYTE), 
	"ACTUAL_TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"REF_CODE" VARCHAR2(50 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"SHIPMENT_ID" VARCHAR2(50 BYTE), 
	"ETA_DESTINATION" DATE, 
	"REPORTED_TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"ACTIVITY" VARCHAR2(1 BYTE), 
	"COMMENTS" VARCHAR2(200 BYTE), 
	"SAP_INV_WEIGHT" NUMBER, 
	"IS_PUC" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"IS_FITNESS_CERT" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"IS_INSURANCE" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"IS_SEATBELT" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"IS_FIRE_EXTENGUISHER" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"IS_EMERGENCY_CARD" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"IS_FIRST_AID" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"IS_SPARK_ARRESTOR" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"SAP_INV_VALUE" NUMBER, 
	"E_WAY_BILL_NO" VARCHAR2(200 BYTE), 
	"DEST_COUNTRY" VARCHAR2(5 BYTE), 
	"REP_WAIT_HRS" NUMBER, 
	"E_WAY_BILL_DATE" DATE, 
	"REP_GO_HRS" NUMBER, 
	"GI_REL_HRS" NUMBER, 
	"LO_REL_HRS" NUMBER, 
	"REL_GO_HRS" NUMBER, 
	"LOC_WAIT_HRS" NUMBER, 
	"CALL_REL_HRS" NUMBER, 
	"TT_DAYS" NUMBER DEFAULT null
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."INDENT_ID" IS 'Indent number against with the truck reports. Will be blank for RM Inbound';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."TYPE" IS 'Type of Truck viz. FGS / RMS';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."SERVPROV" IS 'Transporter (from Indent if available)';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."TRUCK_TYPE" IS 'Truck type (from indent if available)';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."REPORTING_LOCATION" IS 'Default location from where the entry is made. Mapped to gate user';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."SOURCE_LOC" IS 'Source location (from indent if available)';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."DEST_LOC" IS 'Destination location (from indent if available)';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."DEREPORTING_DATE" IS 'Date time entered to close the reporting in case truck was reported but not used';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."STATUS" IS 'Status of the truck -> REPORTED, GATED_IN, LOADING, UNLOADING, LOADED, INTRANSIT, GEOFENCE_IN, RECEIVED, DELIVERED';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."REJ_STATUS" IS 'Rejection status of the truck -> NORMAL, REJECTED';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."IN_WEIGHT" IS 'Weight of truck when coming into reporting location';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."OUT_WEIGHT" IS 'Weight of truck when going out of reporting location';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."NET_WEIGHT" IS 'Difference of scale weight -> |OUT_WEIGHT – IN_WEIGHT|';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."BAY" IS 'Bay to which the truck is assigned';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."BAY_STATUS" IS 'Bay Status: ARVD, WAIT, CALL, LSPB, LFPB, CLOSED';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."ACTUAL_TRUCK_TYPE" IS 'Actual truck type as recorded by FGS';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."ETA_DESTINATION" IS 'ETA_DESTINATION + TT';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."SAP_INV_WEIGHT" IS 'SAP Invoice Weight';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING"."TT_DAYS" IS 'Transit Time';
