--------------------------------------------------------
--  DDL for Table TRUCK_REPORTING_SUMMARY
--------------------------------------------------------

  CREATE TABLE "ATOM"."TRUCK_REPORTING_SUMMARY" 
   (	"REPORTING_LOC" VARCHAR2(20 BYTE), 
	"TRUCKS_REPORTED" NUMBER, 
	"TRUCKS_GATEDIN" NUMBER, 
	"EXCESS_WAITING_REP" NUMBER, 
	"EXCESS_WAITING_LOC" NUMBER, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"TRUCKS_LOADINGIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;

   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING_SUMMARY"."TRUCKS_REPORTED" IS 'Sum of all records where status is REPORTED';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING_SUMMARY"."TRUCKS_GATEDIN" IS 'Sum of all records where status is GATED_IN';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING_SUMMARY"."EXCESS_WAITING_REP" IS 'Sum of all records where status is REPORTED and WAIT_TIME_HRS > X HRS (from MT_EXCESS_WAITING_REP_LIMIT)';
   COMMENT ON COLUMN "ATOM"."TRUCK_REPORTING_SUMMARY"."EXCESS_WAITING_LOC" IS 'Sum of all records where status is GATED_IN and WAIT_TIME_HRS > X HRS (from MT_EXCESS_WAITING_LOC_LIMIT)';
