--------------------------------------------------------
--  DDL for Table UM_USER_ROLE
--------------------------------------------------------

  CREATE TABLE "ATOM"."UM_USER_ROLE" 
   (	"USER_ROLE_ID" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"INSERT_DATE" DATE, 
	"INSERT_USER" VARCHAR2(50 BYTE), 
	"UPDATE_USER" VARCHAR2(50 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
