--------------------------------------------------------
--  DDL for Table XX_SHIPMENT
--------------------------------------------------------

  CREATE TABLE "ATOM"."XX_SHIPMENT" 
   (	"SHIPMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SHIPMENT_NAME" VARCHAR2(20 BYTE), 
	"SHIPMENT_TYPE" VARCHAR2(20 BYTE), 
	"SERVPROV" VARCHAR2(50 BYTE), 
	"TRANSPORTER_SAP_CODE" VARCHAR2(50 BYTE), 
	"TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"TRUCK_NUMBER" VARCHAR2(20 BYTE), 
	"ACTUAL_TRUCK_TYPE" VARCHAR2(20 BYTE), 
	"VARIANT_1" VARCHAR2(20 BYTE), 
	"VARIANT_2" VARCHAR2(20 BYTE), 
	"INDENT_ID" VARCHAR2(100 BYTE), 
	"DRIVER_LICENSE" VARCHAR2(50 BYTE), 
	"DRIVER_MOBILE" VARCHAR2(50 BYTE), 
	"DRIVER_NAME" VARCHAR2(100 BYTE), 
	"FREIGHT" NUMBER, 
	"FREIGHT_UOM" VARCHAR2(5 BYTE), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"TOTAL_QTY" NUMBER, 
	"TOTAL_TTE" NUMBER, 
	"TOTAL_WEIGHT" NUMBER, 
	"TOTAL_WEIGHT_UOM" VARCHAR2(5 BYTE), 
	"TOTAL_VOLUME" NUMBER, 
	"TOTAL_VOLUME_UOM" VARCHAR2(5 BYTE), 
	"TTE_UTIL" NUMBER, 
	"WEIGHT_UTIL" NUMBER, 
	"VOLUME_UTIL" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"STOP_TYPE" VARCHAR2(10 BYTE), 
	"CONTAINER_NUM" VARCHAR2(20 BYTE), 
	"SHIPPED_ONBOARD_DATE" DATE, 
	"DEST_COUNTRY" VARCHAR2(5 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
