--------------------------------------------------------
--  DDL for Table XX_SHIPMENT_LOADSLIP_LINE
--------------------------------------------------------

  CREATE TABLE "ATOM"."XX_SHIPMENT_LOADSLIP_LINE" 
   (	"LOADSLIP_ID" VARCHAR2(20 BYTE), 
	"LINE_NO" NUMBER, 
	"ITEM_ID" VARCHAR2(20 BYTE), 
	"QTY" NUMBER, 
	"BATCH_CODE" VARCHAR2(10 BYTE), 
	"SO_STO_NUMBER" VARCHAR2(100 BYTE), 
	"INVOICE_NUMBER" VARCHAR2(100 BYTE), 
	"INVOICE_DATE" DATE, 
	"LR_NUMBER" VARCHAR2(100 BYTE), 
	"LR_DATE" DATE, 
	"DELIVERY_NUMBER" VARCHAR2(100 BYTE), 
	"GRN_NUMBER" VARCHAR2(100 BYTE), 
	"GRN_DATE" DATE, 
	"REPORTING_DATE" DATE, 
	"UNLOADING_DATE" DATE, 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
