--------------------------------------------------------
--  DDL for Table XX_SHIPMENT_LOADSLIP
--------------------------------------------------------

  CREATE TABLE "ATOM"."XX_SHIPMENT_LOADSLIP" 
   (	"SHIPMENT_ID" NUMBER, 
	"LOADSLIP_ID" VARCHAR2(20 BYTE), 
	"LOADSLIP_TYPE" VARCHAR2(10 BYTE), 
	"SOURCE_LOC" VARCHAR2(10 BYTE), 
	"DEST_LOC" VARCHAR2(10 BYTE), 
	"DROP_SEQ" NUMBER, 
	"REPORTING_DATE" DATE, 
	"GATE_IN_DATE" DATE, 
	"CONFIRM_DATE" DATE, 
	"RELEASE_DATE" DATE, 
	"GATE_OUT_DATE" DATE, 
	"E_WAY_BILL_NO" VARCHAR2(200 BYTE), 
	"E_WAY_BILL_DATE" DATE, 
	"CUSTOM_INV_NUM" VARCHAR2(2000 BYTE), 
	"INSERT_USER" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"PAAS_SHIP_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1845682454237562" ;
