--------------------------------------------------------
--  File created - Wednesday-October-28-2020   
--------------------------------------------------------
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DROP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\APP_PLAN_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\APP_PLAN_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\BATCH_CODE_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\BATCH_CODE_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISP_PLAN_BOM_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISP_PLAN_BOM_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISP_PLAN_SUMMARY_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISP_PLAN_SUMMARY_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ELR_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ELR_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\EXCESS_TIME_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\EXCESS_TIME_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\EXP_SHIP_CSV_LINE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\EXP_SHIP_CSV_TAB.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\EXP_SHIP_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\EXP_SHIP_TAB.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\FREIGHT_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\FREIGHT_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\FREIGHT_DATA_UPD_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\FREIGHT_DATA_UPD_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ITEM_ARRAY.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ITEM_BOM_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ITEM_BOM_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ITEM_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ITEM_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOCATION_BAY_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOCATION_BAY_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOCATION_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOCATION_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOCATION_SCAN_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOCATION_SCAN_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LS_DASHBOARD_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LS_DASHBOARD_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LS_DASHBOARD_UI_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LS_DASHBOARD_UI_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MATERIAL_GROUP_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MATERIAL_GROUP_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_VALVE_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_VALVE_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ORDER_TYPE_LOOKUP_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ORDER_TYPE_LOOKUP_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SAP_TRUCK_TYPE_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SAP_TRUCK_TYPE_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SERVPROV_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SERVPROV_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIP_DETAILS.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIP_DETAILS_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIP_STOP_DETAILS_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIP_STOP_DETAILS_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\STRING_TAB.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRANSPORTER_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRANSPORTER_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_TYPE_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_TYPE_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_TYPE_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_TYPE_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\T_CSV_LINE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\T_CSV_TAB.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\T_DATE_ARRAY.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\T_NUM_ARRAY.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\T_STR_ARRAY.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UPD_MATERIAL_GROUP_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UPD_MATERIAL_GROUP_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UPD_SAP_TRUCK_TYPE_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UPD_SAP_TRUCK_TYPE_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UPD_TRUCK_TYPE_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UPD_TRUCK_TYPE_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\USER_ASSOCIATION_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\USER_ASSOCIATION_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\USER_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\USER_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\USER_ROLE_DATA_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\USER_ROLE_DATA_OBJ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DEPT_SEQ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_SEQ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\EMP_SEQ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ERROR_RECORDS_SEQ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\FILE_ULOAD_SEQ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INDENT_SUMMARY_SEQ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INTEGRATION_ERROR_SEQ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INTEGRATION_SEQ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___112957.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___118561.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___123478.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___133823.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___138989.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___138991.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___143876.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___196859.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___226702.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___226707.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___87249.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___87265.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___87297.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___87412.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___89109.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___93745.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ISEQ___95928.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_SEQ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\PAAS_MASTER_DATA_SEQ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\RUNNING_ID_GENERATION_SEQ.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_TYPE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\APEX_TEAM_DEV_FILES.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_MASTER_ERROR_DETAILS.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_OTM_INTEGRATION_AUDIT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATOM_UPLOAD_FILES.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\BUSINESS_NUMBER_SEQUENCE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CLS_FILE_DATA.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CREATE_JAVA_LOB_TABLE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_COUNTRY.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_GPS.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_LANE_TYPE_LOOKUP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_OTM_FREIGHT_BASIS.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_RATE_TYPE_LOOKUP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_REJECTION_CODE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_SCALE_INVOICE_WT_DIFF.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_UOM.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_UOM_MAP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DEL_INV_HEADER.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DEL_INV_LINE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_BOM.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_SUMMARY.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_T.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_TEMP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_T_ERROR.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISP_PLAN.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\FREIGHT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\FREIGHT_TEMP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\FREIGHT_TEMP_NOTIFY.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GRN_DETAIL_SO.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GRN_HEADER.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GRN_LINE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\HTMLDB_PLAN_TABLE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INDENT_DETAIL.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INDENT_SUMMARY.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INTEGRATION_ERRORS.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INTEGRATION_LOG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\JSON_CLOB.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_DETAIL.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_DETAIL_BOM.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_INV_HEADER.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_INV_LINE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_LINE_DETAIL.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOCATION_SCAN.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOCATION_SCAN_BKP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_BATCH_CODES.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_CONTACT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_CUSTOMER.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_CUSTOMER_SHIP_TO.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_DRIVER.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ELR.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_EXCESS_WAITING_LOC_LIMIT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_EXCESS_WAITING_REP_LIMIT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_EXT_WAREHOUSE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_INCOTERMS.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_OE_BOM.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_OE_BOM_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_PLANT_WEIGHT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_REP_BOM.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_LANE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_LOCATION.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_LOCATION_BAY.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_MATERIAL_GROUP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_PLANT_BATCH.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_SAP_TRUCK_TYPE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_SCAC.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_SUPPLIER.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRANSPORTER.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_DEDICATED.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_DEDICATED_AUDIT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_TYPE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_TYPE_BKP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_USAGE_CODE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_VALVE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ORDER_TYPE_LOOKUP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\PLANT_CONTACT_DETAILS.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHARED_TRUCK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_EXPORT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_STOP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRG_LOG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_REPORTING.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_REPORTING_SUMMARY.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UM_USER.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UM_USER_ASSOCIATION.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UM_USER_ROLE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XSL_STYLESHEET.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_JSON_DOCUMENT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_LOADSLIP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_LOADSLIP_LINE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\BUSINESS_NUMBER_SEQUENCE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_GPS_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_OTM_FREIGHT_BASIS_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_RATE_TYPE_LOOKUP_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_REJECTION_CODE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DEL_INV_HEADER_N1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DEL_INV_HEADER_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DEL_INV_LINE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_BOM_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_N1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_T_ERROR_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_T_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_T_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISP_PLAN_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GRN_DETAIL_SO_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GRN_DETAIL_SO_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GRN_HEADER_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GRN_LINE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INDENT_DETAIL_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INDENT_SUMMARY_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INDENT_SUMMARY_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INTEGRATION_ERRORS_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INTEGRATION_LOG_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INTEGRATION_LOG_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_DETAIL_BOM_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_DETAIL_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_DETAIL_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_INV_HEADER_N1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_INV_HEADER_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_INV_LINE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_LINE_DETAIL_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOCATION_SCAN_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_BATCH_CODES_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_CONTACT_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_CUSTOMER_SHIP_TO_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_CUSTOMER_SHIP_TO_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_DRIVER_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ELR_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_EXCESS_WAITING_LOC_LIMI_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_EXCESS_WAITING_REP_LIMIT_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_INCOTERMS_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_OE_BOM_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_PLANT_WEIGHT_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_REP_BOM_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_LANE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_LOCATION_BAY_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_LOCATION_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_MATERIAL_GROUP_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_MATERIAL_GROUP_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_SAP_TRUCK_TYPE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_SCAC_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_SUPPLIER_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRANSPORTER_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRANSPORTER_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_TYPE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_VALVE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ORDER_TYPE_LOOKUP_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHARED_TRUCK_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_EXPORT_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_STOP_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_C0016079.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_C0079245.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000083411C00008__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000090072C00001__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000092550C00005__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000092550C00013__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000118777C00002__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000120275C00001__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000120482C00005__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000120482C00006__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000141076C00017__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000143871C00001__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000143876C00002__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000155951C00002__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000198420C00002__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000222741C00005__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SYS_IL0000222741C00013__.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TABLE1_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRG_LOG_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_REPORTING_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_REPORTING_INDEX2.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_REPORTING_INDEX3.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_REPORTING_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UM_USER_ASSOCIATION_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UM_USER_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UM_USER_ROLE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\USAGE_CODE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_AT_LOCATION_MT_PK1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_JSON_DOCUMENT_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_LOADSLIP_INDEX1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_LOADSLIP_INDEX2.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_LOADSLIP_LINE_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_LOADSLIP_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_PK.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\APEX_TEAM_DEV_FILES_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_MASTER_ERROR_DETAILS_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATOM_UPLOAD_FILES_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\BUSINESS_NUMBER_SEQUENCE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CLS_FILE_DATA_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CREATE_JAVA_LOB_TABLE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_COUNTRY_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_GPS_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_LANE_TYPE_LOOKUP_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_OTM_FREIGHT_BASIS_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_RATE_TYPE_LOOKUP_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_REJECTION_CODE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_SCALE_INVOICE_WT_DIFF_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_UOM_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\CT_UOM_MAP_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DEL_INV_HEADER_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DEL_INV_LINE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_BOM_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_T_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_TEMP_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_T_ERROR_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISP_PLAN_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\FREIGHT_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GRN_DETAIL_SO_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GRN_HEADER_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GRN_LINE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INDENT_DETAIL_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INDENT_SUMMARY_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INTEGRATION_ERRORS_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INTEGRATION_LOG_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_DETAIL_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_DETAIL_BOM_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_INV_HEADER_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_INV_LINE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_LINE_DETAIL_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOCATION_SCAN_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOCATION_SCAN_BKP_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_BATCH_CODES_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_CONTACT_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_CUSTOMER_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_CUSTOMER_SHIP_TO_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_DRIVER_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ELR_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_EXCESS_WAITING_LOC_LIMIT_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_EXCESS_WAITING_REP_LIMIT_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_EXT_WAREHOUSE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_INCOTERMS_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_OE_BOM_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_OE_BOM_LIST_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_PLANT_WEIGHT_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_REP_BOM_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_LANE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_LOCATION_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_LOCATION_BAY_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_MATERIAL_GROUP_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_PLANT_BATCH_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_SAP_TRUCK_TYPE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_SCAC_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_SUPPLIER_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRANSPORTER_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_DEDICATED_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_DEDICATED_AUDIT_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_TYPE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_TYPE_BKP_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_USAGE_CODE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_VALVE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ORDER_TYPE_LOOKUP_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\PLANT_CONTACT_DETAILS_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHARED_TRUCK_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_EXPORT_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_STOP_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRG_LOG_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_REPORTING_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_REPORTING_SUMMARY_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UM_USER_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UM_USER_ASSOCIATION_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UM_USER_ROLE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XSL_STYLESHEET_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_JSON_DOCUMENT_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_LOADSLIP_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_LOADSLIP_LINE_CONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DEL_INV_LINE_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DISPATCH_PLAN_BOM_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\FREIGHT_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GRN_LINE_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INDENT_DETAIL_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INTEGRATION_LOG_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_DETAIL_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_DETAIL_BOM_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_INV_LINE_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_LINE_DETAIL_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_ITEM_OE_BOM_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRANSPORTER_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\MT_TRUCK_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_EXPORT_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SHIPMENT_STOP_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRUCK_REPORTING_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UM_USER_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UM_USER_ASSOCIATION_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_LOADSLIP_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XX_SHIPMENT_LOADSLIP_LINE_REFCONSTRAINT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\APEX_TEAM_DEV_FILES_BIU.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRG_DISPATCH_PLAN_BI.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRG_DISPATCH_PLAN_T_BI.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRG_DISPATCH_PLAN_T_ERROR_BI.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRG_INDENT_SUMMARY_BI.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRG_LOADSLIP_BU.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRG_MT_TRUCK_DEDICATED_BIUD.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TRG_TRUCK_REPORTING_BU.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\V.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\BLOB_TO_CSV.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GET_OTHER_CHARGES.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\STRING_LIST.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TEST_OTM_FREIGHT_OUTBOUND.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XMLTOJSON.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_ACTUAL_SHIP_INT_API.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_APP_CONFIG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_ATOM_API.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_BUSINESS_FLOW_PKG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_INTEGRATION_PKG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_MASTER_DATA_FLOW_PKG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_MASTER_DATA_SETUP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_MASTER_ERROR_HANDLING_PKG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_OTM_INTEGRATION_PKG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_REST_SERVICE_PKG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_SAP_INTEGRATION_PKG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_UTIL_PKG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GET_LOADSLIP_LR_NUM.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DBMS_XMLDOM.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_ACTUAL_SHIP_INT_API_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_ATOM_API_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_BUSINESS_FLOW_PKG_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_INTEGRATION_PKG_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_MASTER_DATA_FLOW_PKG_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_MASTER_DATA_SETUP_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_MASTER_ERROR_HANDLING_PKG_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_OTM_INTEGRATION_PKG_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_REST_SERVICE_PKG_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_SAP_INTEGRATION_PKG_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATL_UTIL_PKG_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\GET_LOADSLIP_LR_NUM_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\ATOM_INTEGRATION_DATA_PURGE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\FREIGHT_NOTIFY_ACCOUNTS.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\INSERT_SHIPMENT_STOPS.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\LOADSLIP_WT_VOL_CAL.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\POST_TO_ATOM.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\SEND_OTM_SHIPMENT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\TEMP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UPDATE_INVOICE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UPDATE_INVOICE_MP_SHIPMENT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UPDATE_SHIPMENTS.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\APEX_WORKSPACES.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\V_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\WWV_FLOW.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\WWV_FLOW_LANG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DUAL.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\APEX_WEB_SERVICE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DBMS_XMLGEN.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XMLAGG.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\XMLTYPE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DBMS_LOB.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DBMS_OUTPUT.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DBMS_SCHEDULER.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\PLITBLM.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UTL_HTTP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\JSON_ARRAY_T.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\JSON_OBJECT_T.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UTL_TCP.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\APEX_JSON.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\APEX_APPLICATION_GLOBAL.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\APEX_MAIL.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\APEX_UTIL.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DBMS_UTILITY.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DBMS_XMLDOM_1.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DBMS_XMLPARSER.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\DBMS_XSLPROCESSOR.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\USER_OBJECTS.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UTL_ENCODE.sql
@D:\OneDrive - Inspirage\Projects\Apollo\Design\ATL-Oracle PaaS-Config\Source Code\Apollo-ATOM-DB\UTL_RAW.sql
